New repository MentorMate
Ivaneff/MentorMate-QA-Academy pull request #3
Opened 2022-06-26 20:45 UTC by Ivaneff

Привет Вальо,

Моля да погледнеш домашните (TestNG/REST Assured). Имаш ли идея защо не се виждат паралелните екзекюшъни на сюит-а? Благодаря!

2022-06-27 07:00 UTC, valyo-nikolov requested changes
Като цяло добре си се справил - радвам се че си упражнил и сам да създадеш рикуест

2022-06-27 07:00 UTC, valyo-nikolov commented on src/main/resources/testng.xml
> +    <test name="sumTest" group-by-instances="true">
Тук тр да добавиш само един път класа в който имаш 5 тест метода. Те ще се изпълнят паралелно един път тъй като си ги конфигурирал на ниво methods

2022-06-27 07:00 UTC, valyo-nikolov commented on src/test/java/restAssuredHomework/LoginDto2.java
> +public class LoginDto2 {
Не е небхдимо да създаваш ново поджо тук - може да преизползваш вече създаденото за първия тест от демото

2022-06-27 07:00 UTC, valyo-nikolov commented on src/test/java/restAssuredHomework/LoggingAuthenticationTests.java
> +        LoginDto2 loginDto = new LoginDto2();
Изнеси поджото от демото си в отдлелен клас и ползвай него и тук пак, вместо да създаваш нов дупликат на този клас

2022-06-28 19:14 UTC, valyo-nikolov approved these changes
Добре, но напиши и един тест от себе си по АПИ-то на Скило.

2022-06-28 19:34 UTC, Ivaneff commented
> 
Благодаря! Ще направя отделен пул рикуест за АПИ-то, тъй като съм с едно домашно назад.

2022-06-28 19:35 UTC, merged